name: marktest2
favicon: null
layout_spectrum: 0.5825675390660763
typography_spectrum: 0.8133173435926437
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.11641620798036456
  lightness: 0.0834765259642154
  saturation: 0.9163729308638722
  rhythmicContrast: 0.1123380889184773
purpose: []
